name: Build release version

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install -r requirements/ci.txt
          pip install -r requirements/base.txt -r requirements/dev.txt

      - name: Versioning
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run: |
          # Verify that the tag has the form X.Y.Z or X.Y.ZrcW, and that it
          # points the HEAD of master.
          GITHUB_TAG="${GITHUB_REF##refs/tags/}"
          [[ $GITHUB_TAG =~ ^[0-9]+.[0-9]+.[0-9]+(rc[0-9]+)?$ ]] && \
          [[ $(git rev-parse master) = $(git rev-parse $GITHUB_TAG) ]] && \
          echo "__version__ = \"${GITHUB_TAG}\"" > pymanopt/_version.py

      - name: Build sdist and wheel
        run: python setup.py sdist bdist_wheel

      - name: Publish to pypi on tags
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
